config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'account_activations/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'contact' => 'static_pages#contact'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new,:create,:edit,:update]
  resources :microposts,          only: [:create,:destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
    The <a href="http://www.railstutorial.org">Ruby On Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
    <ul>
    <li><%= link_to "About", about_path%></li>
    <li><%= link_to "Contact", contact_path%></li>
    <li><a href="http://news.railstutorial.org">News</a></li>
    </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" >
      <div class="container">
        <%= link_to"sample app", root_path, id: 'logo' %>
        <nav>
          <div class="navbar-header">
            <button id="hamburger" type="button" class="navbar-toggle collapsed">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <ul id="navbar-menu" 
              class="nav navbar-nav navbar-right collapse navbar-collapse">
            <li>
              <%= link_to "Home",root_path %>
            </li>
             <li>
              <%= link_to "Help",help_path %>
            </li>
            <%if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" id="account" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= button_to "Log out", logout_path, method: :delete %></li>
              </ul>
            </li>
            <%else%>
             <li>
              <%= link_to "Log in", login_path, method: :get %>
            </li>
            <%end %>
            
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- [if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <%# <%= javascript_include_tag 'rails-ujs', 'data-turbolinks-track': 'reload' %> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>